### ISSUE TITLE
I don't see the module  ("asw"))

### ISSUE THREAD

**Issue by GitMyCode** [JiriSuster/TerrariaFishingBot#2]
the code doesn't work for me. There is not module
for that line `if (module.ModuleName.ToLower().Contains("asw"))`
all i get is 
Module: $terraria.exe
Module: $ntdll.dll
Module: $wow64.dll
Module: $wow64win.dll
Module: $wow64cpu.dll

**Comment by sirhvd** [comment]
Me too. I didn't saw "asw" module even in 1.4.1.1 version. It's weird.

**Comment by JiriSuster** [comment]
I tried to fix this issue by using address from Terraria module, but I am unable to find new address after latest update. That means this repo is currently outdated.
